# -*- coding: utf-8 -*-
"""helloWorld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16137gbzlVhheunlP5ZnAVIC2Al0t-qIy
"""

print("Hello, World!")